### ISSUE TITLE
module is loading / F instead of C / only 5 entries

### ISSUE THREAD

**Issue by SvenPisa** [luxiouronimo/MMM-OpenWeatherMapForecast#6]
I have a few problems with the module or I have made the wrong entries in Config.js. Here is an excerpt 
		{
			module: "MMM-AccuWeatherForecastDeluxe",
			header: "Wettervorhersage",
			position: "top_center",
			classes: "default everyone",
			disabled: false,
			config: {
				apikey: "H5ShqAVZaIGdQDoSrG4uwS31k8Jxxxxx",
				latitude: "xx.615",
				longitude: "xx.087",
				relativeColors: true,
				hourlyForecastLayout: "table",
				maxHourliesToShow: 5,
				dailyForecastLayout: "table",
				maxDailiesToShow: 8,
				ignoreToday: true,
				showPrecipitationProbability: false,
				showPrecipitationSeparator: false,
				showWindGust: false,
				iconset: "4c",
				useAnimatedIcons: false,
				label_ordinals: ['↓', '↙', '←', '↖', '↑', '↗', '→', '↘'],
				label_high: "",
				label_low: "",
				}
		},

1. no data is displayed. The module is continuously set to "Loading...".
2. had previously only used the bar layout. Here, however, "Fahrenheit" was always displayed instead of Celsius as the temperature unit although I selected metric as the unit.
3. and even if I selected maxDailiesToShow: 8, only 5 days were displayed. can someone tell me how I can solve the three problems and in which file I have to make which setting or what has to be entered in the custom.css? Thank you

**Comment by luxiouronimo** [comment]
1. using your config, you need to change:
`module: "MMM-AccuWeatherForecastDeluxe",`
to:
`module: "MMM-OpenWeatherForecastDeluxe",`

2. looking into this…
3. hmm, is it possible they are not providing more than 5 days in the data? i am able to set the maxDailiesToShow up to 8 and it shows the appropriate amount.. i am in the usa but i checked for example munich germany and there are still 8 dailies total provided (today + 7).. are you comfortable probing the web inspector to find the OPENWEATHER_ONE_CALL_FORECAST_DATA and confirm that they are serving 8 dailies?

**Comment by luxiouronimo** [comment]
2. metric units work for me; be sure to set it at config.units; at the same global (not module config) level as address/port/ipWhitelist/etc.

**Comment by luxiouronimo** [comment]
2. regarding the units, they work for me whether specified globally as the default for magicmirror, or locally in the module config; perhaps your issue was related to the module name..?

**Comment by SvenPisa** [comment]
I changed the name but it can't really be related to that because the module is called MMM-AccuWeatherForecastDeluxe and shows like this at the modules.
if i change it to`module: "MMM-OpenWeatherForecastDeluxe",` it is no longer displayed at all.
 maxDailiesToShow is changed up to 8 . but it really shows only 5 Days (i have seen at the bar layout) :-(

So i have no idea... :-(

**Comment by luxiouronimo** [comment]
you have come to the wrong place for support; this module is `MMM-OpenWeatherForecastDeluxe`, you are looking for help with `MMM-AccuWeatherForecastDeluxe`
